easy_admin:
    entities:
      Contact:
        class: App\Entity\Contact
        form:
          fields:
            - { property: 'nom' }
            - { property: 'prenom' }
            - { property: 'email' }
            - { property: 'content' }
            - { property: 'createdAt' }
        list:
          actions:
            - { name: 'edit', icon: 'pencil', label: false, css_class: "btn btn-primary"  }    
            - { name: 'delete', icon: 'trash', label: false, css_class: "btn btn-danger"  } 