easy_admin:
    entities:
      Participation:
        class: App\Entity\Participation
        form:
          fields:
            - { property: 'user' }
            - { property: 'project' }
        list:
          actions:
            - { name: 'edit', icon: 'pencil', label: false, css_class: "btn btn-primary"  }    
            - { name: 'delete', icon: 'trash', label: false, css_class: "btn btn-danger"  } 